### ISSUE TITLE
1.12.2 support

### ISSUE THREAD

**Issue by ghost** [Dutchs/InfernalStages#1]
At the moment, Infernal Stages is only available for version 1.18.2 — a version that almost no one plays because it doesn't have enough other good mods and because it's not the latest. In fact, at the moment the mod is not needed by anyone except you and maybe those who will play with you on the local server. It would be a very good idea to add support for other versions, for example 1.12.2 — the version with the largest number of combat and hardcore mods, which has many players and many more fans of hardcore mods such as Infernal Mobs.

**Comment by Dutchs** [comment]
Sadly building for Minecraft Forge on MC 1.12.2 is currently a nightmare as Forge dropped support for this version of minecraft.
I would if I could.
